// Mathematicians data - full names
const mathematicians = [
  "Andrew Wiles",
  "Archimedes",
  "Aristotle",
  "Ada Lovelace",
  "Alan Turing",
  "Bernoulli family",
  "Blaise Pascal",
  "Brahmagupta",
  "Brook Taylor",
  "Carl Gauss",
  "Carl Jacobi",
  "Charles Babbage",
  "Claude Shannon",
  "Daniel Bernoulli",
  "David Hilbert",
  "Diophantus",
  "Donald Knuth",
  "Euclid",
  "Leonhard Euler",
  "Emmy Noether",
  "Paul Erdős",
  "Fibonacci",
  "Pierre de Fermat",
  "Joseph Fourier",
  "Georg Fechner",
  "Galileo Galilei",
  "Carl Friedrich Gauss",
  "Kurt Gödel",
  "Sophie Germain",
  "Hypatia",
  "Hermann Grassmann",
  "Jacques Hadamard",
  "Isaac Newton",
  "Ibn al-Haytham",
  "Ivar Ekeland",
  "Itō Kiyoshi",
  "Johannes Kepler",
  "Joseph-Louis Lagrange",
  "Julia Robinson",
  "Jean-Pierre Serre",
  "Katherine Johnson",
  "Andrey Kolmogorov",
  "Leopold Kronecker",
  "Kiyosi Itô",
  "Gottfried Leibniz",
  "Sophus Lie",
  "John von Neumann",
  "Benoit Mandelbrot",
  "Andrey Markov",
  "John Napier",
  "Isaac Newton",
  "Niels Abel",
  "Omar Khayyám",
  "Olga Oleinik",
  "Oskar Perron",
  "Mikhail Ostrogradsky",
  "Pythagoras",
  "Henri Poincaré",
  "Qin Jiushao",
  "Daniel Quillen",
  "Qiudong Wang",
  "Qu Wenjun",
  "Bernhard Riemann",
  "Srinivasa Ramanujan",
  "Frank Ramsey",
  "Simon Stevin",
  "Mary Somerville",
  "Thales",
  "Alan Turing",
  "Niccolò Fontana Tartaglia",
  "Teiji Takagi",
  "Stanislaw Ulam",
  "Pavel Urysohn",
  "Ushijima",
  "Ueno Chikako",
  "François Viète",
  "John Venn",
  "Varahamihira",
  "Ivan Vinogradov",
  "Andrew Wiles",
  "John Wallis",
  "Karl Weierstrass",
  "Xenocrates",
  "Xiahou Yang",
  "Xu Guangqi",
  "Xue Xin",
  "Yang Hui",
  "Yutaka Taniyama",
  "Shing-Tung Yau",
  "Yoshida Koyu",
  "Zeno of Elea",
  "Ernst Zermelo",
  "Zhang Heng",
  "Max Zorn",
];

// Formulas list
// Formulas with both names and expressions
const formulas = {
  A: [
    { name: "Area of a circle", expression: "A = πr²" },
    { name: "Arc length formula", expression: "L = rθ" },
    { name: "Arithmetic series sum", expression: "Sₙ = n/2(a₁ + aₙ)" },
  ],
  B: [
    { name: "Binomial theorem", expression: "(a + b)ⁿ = Σ(n choose k)aⁿ⁻ᵏbᵏ" },
    { name: "Bayes' theorem", expression: "P(A|B) = P(B|A)P(A)/P(B)" },
    { name: "Bernoulli's equation", expression: "P + ½ρv² + ρgh = constant" },
  ],
  C: [
    { name: "Cosine rule", expression: "c² = a² + b² - 2ab cos(C)" },
    { name: "Chain rule", expression: "(f∘g)' = (f'∘g)·g'" },
    { name: "Coulomb's law", expression: "F = k(q₁q₂)/r²" },
  ],
  D: [
    { name: "Distance formula", expression: "d = √[(x₂-x₁)² + (y₂-y₁)²]" },
    {
      name: "Derivative definition",
      expression: "f'(x) = lim(h→0)[f(x+h)-f(x)]/h",
    },
    { name: "Divergence theorem", expression: "∭(∇·F)dV = ∯(F·n)dS" },
  ],
  E: [
    { name: "Euler's formula", expression: "eⁱˣ = cos(x) + i sin(x)" },
    { name: "Energy-mass equivalence", expression: "E = mc²" },
    { name: "Exponential growth", expression: "N(t) = N₀eʳᵗ" },
  ],
  F: [
    { name: "Fourier transform", expression: "F(ω) = ∫f(t)e⁻ⁱʷᵗdt" },
    { name: "Fermat's principle", expression: "δ∫n ds = 0" },
    {
      name: "Fundamental theorem of calculus",
      expression: "∫ₐᵇf(x)dx = F(b) - F(a)",
    },
  ],
  G: [
    { name: "Gravitational potential energy", expression: "U = mgh" },
    { name: "Gauss's law", expression: "∯E·dA = Q/ε₀" },
    { name: "Geometric series sum", expression: "S = a/(1 - r)" },
  ],
  H: [
    { name: "Heron's formula", expression: "A = √[s(s-a)(s-b)(s-c)]" },
    { name: "Hooke's law", expression: "F = -kx" },
    { name: "Hubble's law", expression: "v = H₀D" },
  ],
  I: [
    { name: "Ideal gas law", expression: "PV = nRT" },
    { name: "Impulse-momentum", expression: "J = Δp = FΔt" },
    { name: "Induced EMF", expression: "ε = -N(dΦ/dt)" },
  ],
  J: [
    {
      name: "Jacobi identity",
      expression: "[A,[B,C]] + [B,[C,A]] + [C,[A,B]] = 0",
    },
    { name: "Joule's law", expression: "P = I²R" },
    { name: "Jensen's inequality", expression: "φ(∫f dμ) ≤ ∫φ∘f dμ" },
  ],
  K: [
    { name: "Kepler's third law", expression: "T² ∝ a³" },
    { name: "Kinetic energy", expression: "K = ½mv²" },
    { name: "Kutta-Joukowski theorem", expression: "L = ρvΓ" },
  ],
  L: [
    { name: "Law of cosines", expression: "c² = a² + b² - 2ab cos(C)" },
    { name: "Lorentz force", expression: "F = q(E + v×B)" },
    { name: "Logistic growth", expression: "dP/dt = rP(1 - P/K)" },
  ],
  M: [
    {
      name: "Maxwell's equations",
      expression: "∇·E = ρ/ε₀, ∇×E = -∂B/∂t, ...",
    },
    { name: "Mass-energy equivalence", expression: "E = mc²" },
    { name: "Möbius inversion", expression: "g(n) = Σf(d)" },
  ],
  N: [
    { name: "Newton's second law", expression: "F = ma" },
    {
      name: "Navier-Stokes equations",
      expression: "ρ(∂v/∂t + v·∇v) = -∇p + μ∇²v + f",
    },
    { name: "Normal distribution", expression: "f(x) = (1/σ√2π)e⁻⁽ˣ⁻μ⁾²/²σ²" },
  ],
  O: [
    { name: "Ohm's law", expression: "V = IR" },
    { name: "Optical path length", expression: "OPL = ∫n(s)ds" },
    { name: "Orbital velocity", expression: "v = √(GM/r)" },
  ],
  P: [
    { name: "Pythagorean theorem", expression: "a² + b² = c²" },
    { name: "Planck's law", expression: "Bν(T) = (2hν³/c²)/(eʰν/ᵏᵀ - 1)" },
    { name: "Poisson's equation", expression: "∇²φ = -ρ/ε₀" },
  ],
  Q: [
    { name: "Quadratic formula", expression: "x = [-b ± √(b² - 4ac)]/2a" },
    { name: "Quantum harmonic oscillator", expression: "Eₙ = (n + ½)ħω" },
    { name: "Quotient rule", expression: "(f/g)' = (f'g - fg')/g²" },
  ],
  R: [
    { name: "Relativistic energy", expression: "E² = (pc)² + (mc²)²" },
    {
      name: "Rolle's theorem",
      expression: "If f(a)=f(b), ∃c∈(a,b) where f'(c)=0",
    },
    { name: "Rayleigh criterion", expression: "θ = 1.22λ/D" },
  ],
  S: [
    { name: "Schrödinger equation", expression: "iħ∂ψ/∂t = Ĥψ" },
    { name: "Stokes' theorem", expression: "∫∫(∇×F)·dS = ∮F·dr" },
    { name: "Snell's law", expression: "n₁sinθ₁ = n₂sinθ₂" },
  ],
  T: [
    { name: "Taylor series", expression: "f(x) = Σ[f⁽ⁿ⁾(a)/n!](x-a)ⁿ" },
    { name: "Torricelli's law", expression: "v = √(2gh)" },
    { name: "Time dilation", expression: "Δt = γΔt₀" },
  ],
  U: [
    { name: "Uncertainty principle", expression: "σₓσₚ ≥ ħ/2" },
    { name: "Universal gravitation", expression: "F = Gm₁m₂/r²" },
    { name: "Unit circle definition", expression: "eⁱθ = cosθ + i sinθ" },
  ],
  V: [
    { name: "Volume of sphere", expression: "V = (4/3)πr³" },
    { name: "Vector magnitude", expression: "||v|| = √(v₁² + v₂² + v₃²)" },
    {
      name: "Van der Waals equation",
      expression: "(P + a(n/V)²)(V - nb) = nRT",
    },
  ],
  W: [
    { name: "Work-energy theorem", expression: "W = ΔK" },
    { name: "Wien's displacement law", expression: "λₘₐₓT = b" },
    { name: "Wave equation", expression: "∂²u/∂t² = c²∇²u" },
  ],
  X: [
    { name: "X-ray diffraction", expression: "nλ = 2d sinθ" },
    { name: "X-coordinate rotation", expression: "x' = x cosθ - y sinθ" },
    { name: "XOR operation", expression: "A ⊕ B = (A ∨ B) ∧ ¬(A ∧ B)" },
  ],
  Y: [
    { name: "Young's modulus", expression: "E = stress/strain" },
    { name: "Yield strength", expression: "σᵧ = Fᵧ/A₀" },
    { name: "Yukawa potential", expression: "V(r) = -g²(e⁻ᵐʳ)/r" },
  ],
  Z: [
    { name: "Z-transform", expression: "X(z) = Σxₙz⁻ⁿ" },
    { name: "Z-score", expression: "z = (x - μ)/σ" },
    { name: "Zero product property", expression: "If ab=0, then a=0 or b=0" },
  ],
};

// Inventions/Theorems list
const theorems = [
  "Fundamental theorem of calculus",
  "Gödel's incompleteness theorems",
  "Pythagorean theorem",
  "Fermat's Last Theorem",
  "Euclid's Elements",
  // Add more theorems...
];

// Export the data
module.exports = {
  mathematicians,
  formulas,
};
